### ISSUE TITLE
bad command

### ISSUE THREAD

**Issue by pozilei** [monfresh/jekyll-github-actions#1]
Hi monfresh, 

in your article you write:

> First, check if you already have Ruby 2.7.4:
> 
> `chruby 2.7.4`

`chruby` is not a valid command, am I missing something or is `ruby -v` not appropriate?

cheers

**Comment by monfresh** [comment]
Hi @pozilei. Thanks for letting me know about this confusing part of my article.

The article assumes that you are using `chruby`, which comes with my [Ruby on Mac](https://rubyonmac.dev) script.

However, if you already have a working Ruby environment, then you should be able to verify with `ruby -v`. I updated the article. Let me know if it's better now: https://www.moncefbelyamani.com/making-github-pages-work-with-latest-jekyll/

**Comment by pozilei** [comment]
tyvm :)
